services:
  ui:
    build:
      context: ./uis
      dockerfile: Dockerfile
    working_dir: /workspace/uis
    command: ["/usr/local/bin/start.sh"]
    environment:
      NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      NEXT_PUBLIC_AUTH_API_URL: ${NEXT_PUBLIC_AUTH_API_URL}
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - ./:/workspace
      - ui_website_node_modules:/workspace/uis/website/node_modules
      - ui_backoffice_node_modules:/workspace/uis/backoffice/node_modules
    depends_on:
      - api
    networks:
      - healthcore-dev

  api:
    build:
      context: ./services
      dockerfile: Dockerfile
    working_dir: /workspace
    command:
      - uvicorn
      - services.api.main:app
      - --host
      - 0.0.0.0
      - --port
      - "8000"
      - --reload
      - --reload-dir
      - /workspace/services/api
    environment:
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
      JWT_ALGORITHM: ${JWT_ALGORITHM}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      RESET_TOKEN_EXPIRE_MINUTES: ${RESET_TOKEN_EXPIRE_MINUTES}
      RESET_TOKEN_SECRET_KEY: ${RESET_TOKEN_SECRET_KEY}
      RESEND_API_KEY: ${RESEND_API_KEY}
      RESEND_FROM_EMAIL: ${RESEND_FROM_EMAIL}
      FRONTEND_RESET_PASSWORD_URL: ${FRONTEND_RESET_PASSWORD_URL}
    ports:
      - "8000:8000"
    volumes:
      - ./services:/workspace/services
    networks:
      - healthcore-dev

networks:
  healthcore-dev:
    driver: bridge

volumes:
  ui_website_node_modules:
  ui_backoffice_node_modules:
