create table if not exists public.dlq_tasks (
    id bigint generated by default as identity primary key,
    task_id varchar(64) not null unique,
    task_name varchar(128) not null,
    attempt integer not null check (attempt > 0),
    error_message text not null,
    created_at timestamptz not null default now()
);

create index if not exists dlq_tasks_created_at_idx on public.dlq_tasks (created_at);

alter table public.dlq_tasks enable row level security;
